### PR TITLE
Refactor misc parts

### PR DESCRIPTION
**Pull request by vegarringdal**
- (clearDOM) replace setTimeout with requestAnimationFrame

Nicer when it updated faster

- (customElementHMR) : refactor - set cache to CustomElementRegistry

@kyr0 what do you think, keeping the cache  for HMR under CustomElementRegistry ?
Feels cleaner

### CODE REVIEW

**Comment by kyr0** [comment]
Hi :)

hmm yeah, the idea is good, but... Yesterday I had the same idea in mind, but I wasn't sure if the global object `CustomElementRegistry` is writable for properties in all browsers.

I remember when I tried to polyfill `console` in IE some years ago and ran into an error with a live system because I lacked tests for this browser/feature combination. In all major browsers I could polyfill it, except IE. That taught me a painful lesson. So as of my knowledge, internal API's are not standardized to be mutable. So we cannot surely know if today or at some point in time in the future an internal implementation like that changes and the object becomes sealed. 

For the same reason I reverted my caching method where I stored the pointer to the last impl. constructor on the defined impl. itself.

What do you think?

**Comment by vegarringdal** [comment]
Agree, hard to say if someone will seal it in a browser update and break everything.
Lets it like we had it on window.
Should we rename the variable ? `customElementCache`

Any comments about using the requestAnimation ?

**Comment by vegarringdal** [comment]
@kyr0 

Just did a update, have a look.
Still have "dist" in gitignore until we are more ready

**Comment by kyr0** [comment]
Looks good to me :)

**Pull request merged**
